import { Camera, Hospital, Incident, Notification, SystemHealth, SystemSettings, User, AuditLog } from '../types';

export const mockUsers: User[] = [
  {
    id: 'u-admin-001',
    username: 'admin',
    email: 'admin@safeway.gov.in',
    full_name: 'Chief Control Officer (Admin)',
    phone_number: '+919876543210',
    role: 'admin',
    is_active: true,
    is_verified: true,
    created_at: '2026-01-01T00:00:00Z',
    last_login: new Date().toISOString(),
  },
  {
    id: 'u-op-001',
    username: 'operator',
    email: 'operator@safeway.gov.in',
    full_name: 'Highway Patrol Operator',
    phone_number: '+919876543211',
    role: 'operator',
    is_active: true,
    is_verified: true,
    created_at: '2026-01-15T00:00:00Z',
    last_login: new Date().toISOString(),
  },
  {
    id: 'u-viewer-001',
    username: 'viewer',
    email: 'viewer@safeway.gov.in',
    full_name: 'Traffic Analyst Viewer',
    phone_number: '+919876543212',
    role: 'viewer',
    is_active: true,
    is_verified: true,
    created_at: '2026-02-01T00:00:00Z',
    last_login: new Date().toISOString(),
  }
];

export const mockCameras: Camera[] = [
  {
    id: 'cam-uuid-001',
    camera_id: 'CAM-NH48-KM245',
    name: 'NH-48 KM 245 Toll Plaza North',
    camera_type: 'ip_cctv',
    location_name: 'NH-48 KM 245 (Delhi-Jaipur Express Corridor)',
    latitude: 28.4595,
    longitude: 77.0266,
    description: 'High-definition 4K PTZ CCTV overlooking north toll junction',
    status: 'monitoring',
    is_monitoring: true,
    health_score: 98,
    last_active_at: new Date().toISOString(),
    last_detection_at: new Date(Date.now() - 360000).toISOString(),
    total_detections: 14,
    uptime_percentage: 99.8,
    created_at: '2026-01-10T08:00:00Z',
    connection_config: {
      stream_endpoint: 'https://images.unsplash.com/photo-1545178803-4056771d60a3?auto=format&fit=crop&w=1200&q=80',
      rtsp_url: 'rtsp://nhai-camera-hub.internal/live/cam-01'
    }
  },
  {
    id: 'cam-uuid-002',
    camera_id: 'CAM-NH44-KM112',
    name: 'NH-44 KM 112 Flyover Overpass',
    camera_type: 'ip_cctv',
    location_name: 'NH-44 KM 112 (Panipat Highway Section)',
    latitude: 28.7041,
    longitude: 77.1025,
    description: 'Wide-angle surveillance camera monitoring fast lane merging zone',
    status: 'monitoring',
    is_monitoring: true,
    health_score: 95,
    last_active_at: new Date().toISOString(),
    last_detection_at: new Date(Date.now() - 720000).toISOString(),
    total_detections: 28,
    uptime_percentage: 99.4,
    created_at: '2026-01-12T09:30:00Z',
    connection_config: {
      stream_endpoint: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      rtsp_url: 'rtsp://nhai-camera-hub.internal/live/cam-02'
    }
  },
  {
    id: 'cam-uuid-003',
    camera_id: 'CAM-MEW-KM088',
    name: 'Mumbai-Pune Expressway KM 88 Ghats',
    camera_type: 'ip_cctv',
    location_name: 'Mumbai-Pune Expressway Khandala Slope',
    latitude: 18.7562,
    longitude: 73.3429,
    description: 'Weather-hardened IR thermal and optical dual feed for mountain highway',
    status: 'monitoring',
    is_monitoring: true,
    health_score: 92,
    last_active_at: new Date().toISOString(),
    last_detection_at: new Date(Date.now() - 1440000).toISOString(),
    total_detections: 9,
    uptime_percentage: 98.9,
    created_at: '2026-02-05T11:00:00Z',
    connection_config: {
      stream_endpoint: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80',
      rtsp_url: 'rtsp://nhai-camera-hub.internal/live/cam-03'
    }
  },
  {
    id: 'cam-uuid-004',
    camera_id: 'CAM-SYS-WEBCAM',
    name: 'Local Operations Workstation USB Cam',
    camera_type: 'system',
    location_name: 'Control Room Hub 04 Desk',
    latitude: 28.6139,
    longitude: 77.2090,
    description: 'Direct browser-connected USB / Integrated webcam feed for live AI edge inference',
    status: 'online',
    is_monitoring: false,
    health_score: 100,
    last_active_at: new Date().toISOString(),
    total_detections: 3,
    uptime_percentage: 100.0,
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'cam-uuid-005',
    camera_id: 'CAM-MOB-PATROL1',
    name: 'Highway Patrol Mobile Unit 09',
    camera_type: 'mobile',
    location_name: 'Mobile Patrol Unit Van (En route NH-48)',
    latitude: 28.5200,
    longitude: 77.0800,
    description: 'Smartphone / Tablet field browser stream via WebRTC/transcode uplink',
    status: 'online',
    is_monitoring: false,
    health_score: 88,
    last_active_at: new Date().toISOString(),
    total_detections: 6,
    uptime_percentage: 94.2,
    created_at: '2026-03-05T12:00:00Z',
  },
  {
    id: 'cam-uuid-006',
    camera_id: 'CAM-NH24-KM054',
    name: 'NH-24 Bridge Sector 62 Underpass',
    camera_type: 'ip_cctv',
    location_name: 'NH-24 KM 54 Ghaziabad Link',
    latitude: 28.6280,
    longitude: 77.3649,
    description: 'Optical CCTV camera (Network cable maintenance scheduled)',
    status: 'offline',
    is_monitoring: false,
    health_score: 0,
    last_active_at: new Date(Date.now() - 86400000).toISOString(),
    total_detections: 19,
    uptime_percentage: 82.5,
    created_at: '2026-01-20T14:00:00Z',
  }
];

export const mockHospitals: Hospital[] = [
  {
    id: 'hosp-001',
    name: 'Apex Trauma & Multi-Specialty Hospital',
    hospital_code: 'HOSP-APEX-01',
    phone_numbers: ['+919876543201', '+911145678901'],
    email: 'emergency@apextrauma.org',
    address: 'Sector 44, Near NH-48 Expressway Interchange',
    city: 'Gurugram',
    state: 'Haryana',
    postal_code: '122003',
    latitude: 28.4550,
    longitude: 77.0320,
    emergency_contact: 'Dr. R. Sharma (Head of Trauma - 24/7)',
    has_emergency_dept: true,
    has_trauma_center: true,
    has_ambulance: true,
    bed_capacity: 450,
    available_beds: 34,
    is_available: true,
    is_24_7: true,
    accepts_sms: true,
    accepts_email: true,
    accepts_call: true,
    average_response_time_minutes: 3.2,
    total_responses: 142,
    successful_responses: 139,
    description: 'Level 1 Trauma Center with 12 Advanced Life Support (ALS) Ambulances and Helipad.',
    is_active: true,
    is_verified: true,
    created_at: '2026-01-01T00:00:00Z',
    last_notified_at: new Date(Date.now() - 180000).toISOString()
  },
  {
    id: 'hosp-002',
    name: 'Metro City Government Emergency Hospital',
    hospital_code: 'HOSP-METRO-02',
    phone_numbers: ['+919876543202', '+911123456789'],
    email: 'casualty@metrohospital.gov.in',
    address: 'Main Ring Road, Civil Lines',
    city: 'New Delhi',
    state: 'Delhi',
    postal_code: '110054',
    latitude: 28.6850,
    longitude: 77.2100,
    emergency_contact: 'Casualty Medical Officer (On Duty)',
    has_emergency_dept: true,
    has_trauma_center: true,
    has_ambulance: true,
    bed_capacity: 800,
    available_beds: 58,
    is_available: true,
    is_24_7: true,
    accepts_sms: true,
    accepts_email: true,
    accepts_call: true,
    average_response_time_minutes: 4.5,
    total_responses: 285,
    successful_responses: 278,
    description: 'Central Government Multi-Specialty Hospital equipped with emergency triage and ICU burn ward.',
    is_active: true,
    is_verified: true,
    created_at: '2026-01-01T00:00:00Z',
    last_notified_at: new Date(Date.now() - 1800000).toISOString()
  },
  {
    id: 'hosp-003',
    name: 'Sanjivani Highway Emergency Care Clinic',
    hospital_code: 'HOSP-SANJ-03',
    phone_numbers: ['+919876543203'],
    email: 'dispatch@sanjivanicare.in',
    address: 'NH-44 Toll Plaza Adjacent Complex, KM 110',
    city: 'Panipat',
    state: 'Haryana',
    postal_code: '132103',
    latitude: 28.7120,
    longitude: 77.0950,
    emergency_contact: 'Emergency Dispatch Desk',
    has_emergency_dept: true,
    has_trauma_center: false,
    has_ambulance: true,
    bed_capacity: 120,
    available_beds: 15,
    is_available: true,
    is_24_7: true,
    accepts_sms: true,
    accepts_email: false,
    accepts_call: true,
    average_response_time_minutes: 5.1,
    total_responses: 67,
    successful_responses: 65,
    description: 'Dedicated Highway Rapid-Response stabilization clinic with 4 GPS-tracked ambulances.',
    is_active: true,
    is_verified: true,
    created_at: '2026-01-15T00:00:00Z'
  },
  {
    id: 'hosp-004',
    name: 'LifeCare Critical Care Center',
    hospital_code: 'HOSP-LIFE-04',
    phone_numbers: ['+919876543204'],
    email: 'er@lifecarecritical.com',
    address: 'Sector 62, Expressway Bypass Rd',
    city: 'Noida',
    state: 'Uttar Pradesh',
    postal_code: '201301',
    latitude: 28.6250,
    longitude: 77.3700,
    emergency_contact: 'Chief of Critical Care',
    has_emergency_dept: true,
    has_trauma_center: true,
    has_ambulance: true,
    bed_capacity: 300,
    available_beds: 22,
    is_available: true,
    is_24_7: true,
    accepts_sms: true,
    accepts_email: true,
    accepts_call: true,
    average_response_time_minutes: 3.8,
    total_responses: 94,
    successful_responses: 92,
    description: 'Specialized neuro-trauma and surgical emergency center on eastern expressway access corridor.',
    is_active: true,
    is_verified: true,
    created_at: '2026-02-01T00:00:00Z'
  }
];

export const mockIncidents: Incident[] = [
  {
    id: 'inc-001',
    incident_id: 'ACC-2026-10-08-001',
    camera_id: 'cam-uuid-001',
    camera_external_id: 'CAM-NH48-KM245',
    detected_at: new Date(Date.now() - 240000).toISOString(),
    accident_detected: true,
    severity: 'high',
    confidence_score: 0.94,
    latitude: 28.4595,
    longitude: 77.0266,
    location_description: 'NH-48 KM 245 Northbound Fast Lane Merging Zone',
    accident_image_url: 'https://images.unsplash.com/photo-1545178803-4056771d60a3?auto=format&fit=crop&w=1200&q=80',
    status: 'notified',
    vehicle_count: 2,
    vehicle_info: {
      vehicles: [
        { type: 'Heavy Commercial Truck', color: 'White', bbox: [0.15, 0.25, 0.45, 0.55], speed_kmh: 68, confidence: 0.96 },
        { type: 'SUV (Sedan Impact)', color: 'Silver', bbox: [0.42, 0.38, 0.35, 0.42], speed_kmh: 82, confidence: 0.93 }
      ],
      total_vehicles: 2,
      estimated_impact_speed_kmh: 75
    },
    ai_event_data: {
      model_version: 'YOLO-v9-Accident-X',
      processing_time_ms: 138,
      collision_type: 'Rear-End High Speed Collision',
      fire_detected: false,
      road_blockage: true
    },
    notification_started_at: new Date(Date.now() - 180000).toISOString(),
    notification_count: 3,
    notes: 'High severity crash detected. Fast lanes 1 and 2 blocked. Rapid response ambulance notification triggered.',
    created_at: new Date(Date.now() - 240000).toISOString(),
    updated_at: new Date(Date.now() - 60000).toISOString()
  },
  {
    id: 'inc-002',
    incident_id: 'ACC-2026-10-08-002',
    camera_id: 'cam-uuid-002',
    camera_external_id: 'CAM-NH44-KM112',
    detected_at: new Date(Date.now() - 1200000).toISOString(),
    accident_detected: true,
    severity: 'medium',
    confidence_score: 0.88,
    latitude: 28.7041,
    longitude: 77.1025,
    location_description: 'NH-44 KM 112 Flyover Exit Ramp',
    accident_image_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    status: 'acknowledged',
    vehicle_count: 2,
    vehicle_info: {
      vehicles: [
        { type: 'Compact Car', color: 'Red', bbox: [0.22, 0.30, 0.32, 0.38], speed_kmh: 45, confidence: 0.89 },
        { type: 'Motorcycle', color: 'Black', bbox: [0.55, 0.45, 0.20, 0.25], speed_kmh: 30, confidence: 0.87 }
      ],
      total_vehicles: 2,
      estimated_impact_speed_kmh: 38
    },
    ai_event_data: {
      model_version: 'YOLO-v9-Accident-X',
      processing_time_ms: 142,
      collision_type: 'Side Swipe during ramp merge',
      fire_detected: false,
      road_blockage: false
    },
    notification_started_at: new Date(Date.now() - 1100000).toISOString(),
    notification_stopped_at: new Date(Date.now() - 700000).toISOString(),
    notification_count: 2,
    acknowledged_at: new Date(Date.now() - 700000).toISOString(),
    acknowledged_by_hospital_id: 'hosp-001',
    acknowledged_by_hospital_name: 'Apex Trauma & Multi-Specialty Hospital',
    acknowledged_responder: 'Dr. Vivek Mehra (Chief EMT)',
    acknowledged_notes: 'ALS Ambulance #04 Dispatched. ETA 6 minutes to NH-44 KM 112.',
    notes: 'Hospital acknowledged and en route. Notifications automatically halted.',
    created_at: new Date(Date.now() - 1200000).toISOString(),
    updated_at: new Date(Date.now() - 700000).toISOString()
  },
  {
    id: 'inc-003',
    incident_id: 'ACC-2026-10-08-003',
    camera_id: 'cam-uuid-003',
    camera_external_id: 'CAM-MEW-KM088',
    detected_at: new Date(Date.now() - 3600000).toISOString(),
    accident_detected: true,
    severity: 'low',
    confidence_score: 0.74,
    latitude: 18.7562,
    longitude: 73.3429,
    location_description: 'Mumbai-Pune Expressway Khandala Slope Curve 4',
    accident_image_url: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80',
    status: 'detected',
    vehicle_count: 1,
    vehicle_info: {
      vehicles: [
        { type: 'Commercial Van', color: 'White', bbox: [0.35, 0.40, 0.40, 0.35], speed_kmh: 0, confidence: 0.76 }
      ],
      total_vehicles: 1,
      estimated_impact_speed_kmh: 20
    },
    ai_event_data: {
      model_version: 'YOLO-v9-Accident-X',
      processing_time_ms: 155,
      collision_type: 'Shoulder Barrier Scraping / Stalled Vehicle',
      fire_detected: false,
      road_blockage: false
    },
    notification_count: 0,
    notes: 'Potential low severity incident / stalled vehicle against guardrail. Requires operator visual verification.',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString()
  },
  {
    id: 'inc-004',
    incident_id: 'ACC-2026-10-07-009',
    camera_id: 'cam-uuid-001',
    camera_external_id: 'CAM-NH48-KM245',
    detected_at: new Date(Date.now() - 86400000).toISOString(),
    accident_detected: true,
    severity: 'high',
    confidence_score: 0.96,
    latitude: 28.4595,
    longitude: 77.0266,
    location_description: 'NH-48 KM 245 Southbound Toll Corridor',
    accident_image_url: 'https://images.unsplash.com/photo-1545178803-4056771d60a3?auto=format&fit=crop&w=1200&q=80',
    status: 'resolved',
    vehicle_count: 3,
    vehicle_info: {
      vehicles: [
        { type: 'Bus', color: 'Blue', bbox: [0.10, 0.20, 0.40, 0.60] },
        { type: 'Car', color: 'White', bbox: [0.50, 0.30, 0.30, 0.35] }
      ],
      total_vehicles: 3
    },
    ai_event_data: {
      collision_type: 'Multi-vehicle pileup'
    },
    notification_count: 4,
    acknowledged_at: new Date(Date.now() - 85000000).toISOString(),
    acknowledged_by_hospital_name: 'Apex Trauma Hospital',
    resolved_at: new Date(Date.now() - 82000000).toISOString(),
    resolved_by: 'Chief Control Officer (Admin)',
    resolution_notes: 'All 4 injured passengers stabilized and evacuated to Apex Trauma. Wreck cleared from highway by NHAI cranes. Normal traffic resumed.',
    notes: 'Incident successfully resolved with zero fatalities.',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 82000000).toISOString()
  }
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    notification_id: 'NOTIF-2026-001-A',
    incident_id: 'inc-001',
    recipient_type: 'hospital',
    hospital_id: 'hosp-001',
    recipient_phone: '+919876543201',
    recipient_email: 'emergency@apextrauma.org',
    recipient_name: 'Apex Trauma Emergency Desk',
    notification_type: 'sms',
    status: 'delivered',
    message: '[EMERGENCY ALERT] Severe Accident detected at NH-48 KM 245 Northbound. 2 vehicles involved. Coordinates: 28.4595, 77.0266. Please dispatch emergency response: https://safeway.gov.in/ack?token=xyz123',
    sent_at: new Date(Date.now() - 180000).toISOString(),
    delivered_at: new Date(Date.now() - 176000).toISOString(),
    retry_count: 0,
    is_repeat: false,
    repeat_sequence: 1,
    created_at: new Date(Date.now() - 180000).toISOString()
  },
  {
    id: 'notif-002',
    notification_id: 'NOTIF-2026-001-B',
    incident_id: 'inc-001',
    recipient_type: 'hospital',
    hospital_id: 'hosp-001',
    recipient_phone: '+919876543201',
    recipient_name: 'Apex Trauma Emergency Desk',
    notification_type: 'sms',
    status: 'delivered',
    message: '[REPEAT ALERT 2/10] Severe Accident awaiting acknowledgment at NH-48 KM 245. High Priority: https://safeway.gov.in/ack?token=xyz123',
    sent_at: new Date(Date.now() - 120000).toISOString(),
    delivered_at: new Date(Date.now() - 117000).toISOString(),
    retry_count: 1,
    is_repeat: true,
    repeat_sequence: 2,
    created_at: new Date(Date.now() - 120000).toISOString()
  },
  {
    id: 'notif-003',
    notification_id: 'NOTIF-2026-001-C',
    incident_id: 'inc-001',
    recipient_type: 'hospital',
    hospital_id: 'hosp-002',
    recipient_phone: '+919876543202',
    recipient_name: 'Metro City Government Emergency',
    notification_type: 'sms',
    status: 'sent',
    message: '[EMERGENCY ALERT 3/10] High severity accident NH-48 KM 245. Response required immediately.',
    sent_at: new Date(Date.now() - 60000).toISOString(),
    retry_count: 2,
    is_repeat: true,
    repeat_sequence: 3,
    created_at: new Date(Date.now() - 60000).toISOString()
  }
];

export const mockSystemSettings: SystemSettings = {
  auto_notification_enabled: true,
  notification_interval_seconds: 60,
  hospital_search_radius_km: 50.0,
  max_hospitals_to_notify: 5,
  max_notification_retries: 10,
  maintenance_mode: false,
  test_mode: false,
  updated_at: new Date().toISOString()
};

export const mockSystemHealth: SystemHealth = {
  status: 'healthy',
  timestamp: new Date().toISOString(),
  database_connected: true,
  scheduler_running: true,
  active_incidents: 2,
  pending_notifications: 1,
  online_cameras: 5,
  maintenance_mode: false,
  uptime_seconds: 142850
};

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log-001',
    username: 'admin',
    action: 'SETTINGS_UPDATE',
    resource_type: 'system_settings',
    endpoint: '/api/v1/admin/settings',
    method: 'PATCH',
    ip_address: '192.168.1.10',
    success: true,
    description: 'Updated notification repeat interval to 60 seconds',
    created_at: new Date(Date.now() - 3600000).toISOString()
  },
  {
    id: 'log-002',
    username: 'operator',
    action: 'INCIDENT_VERIFIED',
    resource_type: 'incident',
    resource_id: 'inc-001',
    endpoint: '/api/v1/incidents/inc-001/verify',
    method: 'POST',
    ip_address: '192.168.1.15',
    success: true,
    description: 'Confirmed high severity collision on NH-48 KM 245',
    created_at: new Date(Date.now() - 200000).toISOString()
  },
  {
    id: 'log-003',
    username: 'system',
    action: 'NOTIFICATION_DISPATCH',
    resource_type: 'notification',
    resource_id: 'notif-001',
    endpoint: '/api/v1/notifications',
    method: 'POST',
    ip_address: '127.0.0.1',
    success: true,
    description: 'Automated SMS dispatched to Apex Trauma Hospital (+919876543201)',
    created_at: new Date(Date.now() - 180000).toISOString()
  }
];
